=== i-velichko/xml_parsing_task2/src/main/resources/data/medicine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/medicines"
        xmlns:tns="http://www.example.org/medicines"
        elementFormDefault="qualified">
    <element name="medicines">
        <complexType>
            <sequence>
                <element name="medicine" type="tns:Medicine" minOccurs="1" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="Medicine">
        <sequence>
            <element name="name" type="string" />
            <element name="farm" type="string" />
            <element name="group" type="tns:Group" />
            <element name="analogs">
                <complexType>
                    <sequence>
                        <element name="analog" type="string" minOccurs="1" maxOccurs="unbounded" />
                    </sequence>
                </complexType>
            </element>
            <element name="versions" type="string" />
        </sequence>
        <attribute name="id" type="ID" use="required" />
        <attribute name="onReceipt" type="boolean" use="required" default="true" />
        <attribute name="price" type="string" use="optional" default="more than 50"/>
    </complexType>

    <complexType name="Version">
        <sequence>
            <element name="certificate" type="string"/>
            <element name="package" type="string"/>  чтобы здесь добавить энам, стаить тайп тнс пэкэдж, а ниже, после комплекс тайп отдельная секция Симпл тайп Пекедж с энамамми
            <element name="dosage" type="string"/>
        </sequence>
    </complexType>


    <simpleType name="Group">
        <restriction base="string">
            <enumeration value="VITAMINS" />
            <enumeration value="CARDIO" />
            <enumeration value="ANTIBIOTICS" />
            <enumeration value="PAIN RELIEVERS" />
        </restriction>
    </simpleType>

</schema>

<!--<element name="medicine"-->
<!--         type="string"-->
<!--         minOccurs="1"-->
<!--         maxOccurs="unbounded"/>-->
<!--<element name="name"/>-->
<!--<element name="farm" type="string"/>-->
<!--<element name="group" type="string"/>-->
<!--<element name="analogs" type="string"/>-->
<!--<element name="versions" type="string"/>-->

<!--<attribute name="onReceipt" type="boolean" default="true" use="required" />-->
<!--<attribute name="price" use="optional" default="more than 50"/>-->

<!--<simpleType name="ddd">-->
<!--<restriction base="string">-->
<!--    <enumeration value="less than 10"></enumeration>-->
<!--    <enumeration value="less than 20"></enumeration>-->
<!--    <enumeration value="less than 30"></enumeration>-->
<!--    <enumeration value="more than 50"></enumeration>-->
<!--</restriction>-->
<!--</simpleType>-->

=== i-velichko/xml_parsing_task2/src/main/resources/data/medicine.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicines
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.org/devices"
        xsi:schemaLocation="medicine.xsd">
    <medicine onReceipt="false" >
        <name>Магний B6</name>
        <farm>Санофи</farm>
        <group>VITAMINES</group>
        <analogs>
            <analog>sdsdfsdf</analog>
            <analog>Магнелек</analog>
            <analog>Магвит</analog>
            <analog>Магнетаб</analog>
        </analogs>
        <versions>
            <version myType="таблетки"> <!--attribute enum here-->
                <certificate>Рег. №: 10476/16 от 27.04.2016 - Действующее</certificate>
                <package>Таблетки, покрытые оболочкой 470 мг+5 мг: 50 шт.</package>
                <dosage>По 2 таблетки, 3 раза в день,</dosage>
            </version>
            <version>
                <certificate>Рег. №: 9120/09/14/17 от 02.12.2014 - Действующее</certificate>
                <package>Раствор для приема внутрь: 10 мл амп. 10 шт.</package>
                <dosage>3-4 ампулы в сутки, разделенные на 2-3 приема во время еды.</dosage>
            </version>
        </versions>
    </medicine>
</medicines>
